/*// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyfirstBlackMetalAlbum.com.Models;

public partial class TestTable
{
    public string Name { get; set; }
} */