// <auto-generated> This file has been auto-generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyfirstBlackMetalAlbum.com.Models
{
    public partial class Users
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This line configures it as an identity column
        public int UserIntId { get; set; } // New property for the user identifier

        public string Username { get; set; }

        public string PasswordHash { get; set; }

        public string Email { get; set; }

        public byte[] ProfileImage { get; set; }

        public DateTime RegistrationDate { get; set; }

        public int ProgressPercentage { get; set; } // Percentage of the course completed

        public int BeginnerProgress { get; set; } // Percentage of the course completed

        public int IntermediateProgress { get; set; } // Percentage of the course completed

        public int AdvancedProgress { get; set; } // Percentage of the course completed

        public int RecordingProgress { get; set; } // Percentage of the course completed

        // Navigation property for UserProgress
        public ICollection<UserProgress> UserProgresses { get; set; }

    }
}
